### ISSUE TITLE
Einstellungen: Nutzername Chat

### ISSUE THREAD

**Issue by tpohrer** [MobileComputingHof/GPSTracker#11]
Soll der Nutzername der im Chat angezeigt wird in den Einstellungen einstellbar sein? Eigentlich war geplant, dass das immer der Facebook-Nutzername ist. Aber von mir aus können wir das auch über die Einstellungen lösen.

**Comment by drui** [comment]
War nur ein Test was man da so machen kann.

**Comment by lmoedl** [comment]
Der Nutzername ist immer der Facebook-Benutzername!

**Comment by drui** [comment]
Deswegen hatte ich ja auch geschrieben es war nur ein Test wie das mit den Einstellungen so geht.

**Comment by lmoedl** [comment]
Deswegen ist der Issue jetzt auch geclosed

**Comment by apoehlmann** [comment]
Lothar du hast es selbst geclosed
