### ISSUE TITLE
Die Klasse Geopoint ist nur für die MapView/MapController

### ISSUE THREAD

**Issue by apoehlmann** [MobileComputingHof/GPSTracker#14]
Besser ist die Klasse Location, da sie auch das Aufnahmedatum speichert

**Comment by lmoedl** [comment]
Wozu ist das Aufnahmedatum notwendig?
GeoPoints sind für die aktuelle Karte besser geeignet, da sie direkt so wie sie sind verwendet werden können. Bei der Klasse Location muss wieder extra mit der Latitude und Longitude hantiert werden. Und die Klasse Location bietet sonst auch keine signifikanten Vorteile, da andere Kartendienste, wie z. B. Google Maps wieder mit ihrer eigenen Klasse LatLng arbeitet.

**Comment by apoehlmann** [comment]
damit ich nachvollziehen kann wann der Punkt aufgenommen wurde, sonst hast du keine Möglichkeit später die Tracks zeitlich zu vergleichen und die Zeitpunkt der Aufnahme spielt beim Orten auch eine Rolle.

Die Klasse Location von android ist eine Standardklasse ,welche ich vom Locationlistener bekomme. Wieso sollte ich dann plötzlich Geopoints nehmen, die das Gleiche ist wie Location?
