### ISSUE TITLE
Jeden Track in eigener Datei speichern

### ISSUE THREAD

**Issue by lmoedl** [MobileComputingHof/GPSTracker#15]
Es wäre sinnvoll jeden Track in einer eigenen Datei zu speichern, da 
1. die IDs der Tracks vom Server vergeben werden müssen um Duplikate zu vermeiden und dann der Dateiname direkt die ID sein kann
und 2. werden dann die nicht benötigten Tracks nicht unnötig im Speicher gehalten.

**Comment by apoehlmann** [comment]
War schon immer so, schau in den Code
