### ISSUE TITLE
Überflüssige Interfaces entfernen

### ISSUE THREAD

**Issue by lmoedl** [MobileComputingHof/GPSTracker#16]
Ich habe mit Herr Stepping schon darüber gesprochen und es ist uns beiden aufgefallen, dass doch einige Interfaces existieren, die das komplette Programm unnötig kompliziert zum Nachvollziehen machen. Ganz besonders möchte ich hier auf die Klasse Model, sowie das ModelInterface abzielen. @apoehlmann, wieso kann nicht jede Klasse gleich das Interface Serializable implementieren?

**Comment by apoehlmann** [comment]
Das Interface für den Controller ist ja schon rausgefallen. Aber das ModelInterface würde ich drin lassen. Klasse Model kommt raus und allgemein dienen Interfaces als Templates.

**Comment by apoehlmann** [comment]
Model Interface ist entfernt. Ich selber werde trotzdem Interfaces verwenden, dann ist der Code übersichtlicher
