### ISSUE TITLE
Position wird nicht aktualisiert

### ISSUE THREAD

**Issue by r00t65** [MobileComputingHof/GPSTracker#19]
Ich hab mein Handy mit geöffnetem Radar jetzt seit einer halben Std. neben mir liegen und anscheinend wurde die newPosition() Methode kein einziges mal ausgeführt.

Im logcat hab ich keinen Aufruf, in der Post Log vom Server habe ich auch keinen Post von der Methode. Könnte das mal einer bestätigen oder checken?

**Comment by drui** [comment]
Log.i("RadarService", "Service running"); wurde bei mir bei jedem Test ausgeführt und in der Log angezeigt.
Bist du sicher das der Service gestartet wurde?

**Comment by drui** [comment]
Ich hab mal was geändert. 
Service startet und liest den GPS aus.
Wenn nichts am Server ankommt liegt es an der Verbindung oder am Server.

**Comment by r00t65** [comment]
Wenn ich die newPosition() Methode aufrufe funktioniert die Verbindung und der Server, wie schon gesagt ich hab lediglich keinen Aufruf dieser Methode feststellen können.

2147483647	50.298941	11.968903 wird bei mir bei einem manuellen Aufruf der Methode in die DB geschrieben, so wie erwartet.

Jetzt kommt bei mir neuerdings:

> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime: FATAL EXCEPTION: main
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime: Process: de.hof_university.gpstracker, PID: 833
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service de.hof_university.gpstracker.Controller.service.RadarService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2756)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.access$1800(ActivityThread.java:153)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:139)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5267)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:106)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at de.hof_university.gpstracker.Controller.service.RadarService.<init>(RadarService.java:32)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Native Method)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.Class.newInstance(Class.java:1606)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2753)
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.access$1800(ActivityThread.java:153) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:139) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5267) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927) 
> 01-22 15:56:07.431 833-833/de.hof_university.gpstracker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)

**Comment by drui** [comment]
>  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
>     at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:106)
>     at de.hof_university.gpstracker.Controller.service.RadarService.<init>(RadarService.java:32)

Ich würde sagen du hast nicht die neueste Version.
getApplicationContext gibt es in dem Service nicht mehr. 
Und Zeile 32 ist ein Kommentar.

**Comment by apoehlmann** [comment]
Stimmt die haben wir durch "getBaseContext()" geändert

**Comment by drui** [comment]
Außerdem der Aufruft aus dem Konstruktor geflogen (Zeile 32) und in die onHandleIntent (ca Zeile 40).
Also kann die Fehlermeldung gar nicht mehr stimmen.
https://github.com/MobileComputingHof/GPSTracker/commit/eb23385cc43fb63006440061637f38855a7916bb

**Comment by r00t65** [comment]
Komisch der will bei mir nichts aktualisierten. Irgend wo ist dann schon wieder mein git gestorben -. -

**Comment by apoehlmann** [comment]
wie clonest du das Projekt?

**Comment by r00t65** [comment]
Halt normal, neu aus git und dann nur noch pullen und gucken was zu mergen geht, bzw ob er was überschreiben will aber wenn ich nen pull mach sagt er passt alles nix zu tun
