### ISSUE TITLE
App läuft nicht

### ISSUE THREAD

**Issue by lmoedl** [MobileComputingHof/GPSTracker#2]
Errors im StorageController. @apoehlmann bitte wieder fixen!

**Comment by apoehlmann** [comment]
auskommentieren im Fragment, war eigentlich auch schon auskommentiert

**Comment by apoehlmann** [comment]
Merge-Fehler, es wurde die alte Methode genommen

**Comment by apoehlmann** [comment]
und nächstes mal eine genauere Beschreibung es fehlers
