### ISSUE TITLE
Trackliste wirft Fehler bei Zugriff

### ISSUE THREAD

**Issue by bmairhoermann** [MobileComputingHof/GPSTracker#21]
-Nehme Track auf (in meinem Fall Spaziergang von 5 min.)
- Versuche in der Trackliste drauf zuzugreifen
- LogCat wirft Exception:

![bildschirmfoto 2016-01-24 um 16 29 58](https://cloud.githubusercontent.com/assets/11869474/12537153/4b67f036-c2b8-11e5-9a22-bd9f13fee529.png)

Beim Versuch auf den Track intern zuzugreifen (zum Facebook teilen) schmiert die App ab:

![bildschirmfoto 2016-01-24 um 16 36 11](https://cloud.githubusercontent.com/assets/11869474/12537163/9d2bf6a6-c2b8-11e5-9e56-dbd98fdf2a21.png)

**Comment by lmoedl** [comment]
@bmairhoermann ich hab grad gesehen, dass er bei mir diesen Fehler nicht wirft, aber er macht, nachdem man einen Track ausgewählt hat, trotzdem nichts. Also er zeigt den auf der Karte nicht an

**Comment by lmoedl** [comment]
Oder hast du den Teil wieder rausgemacht?

**Comment by apoehlmann** [comment]
es existiert noch kein Code der den Track vom Speicher in die Karte lädt, da ich mir noch nicht sicher bin wie ich das parallel mit dem Tracking mache

**Comment by apoehlmann** [comment]
Das Laden und Speichern von Tracks hat beim letzten Stand von mir funktioniert

**Comment by apoehlmann** [comment]
Das Laden vom Track funktioniert doch, es kann sein  das du die Dummydaten nicht richtig erstellst
