### ISSUE TITLE
ConntectionController einbauen

### ISSUE THREAD

**Issue by apoehlmann** [MobileComputingHof/GPSTracker#3]
NotificationTrackListener (übergeben an TrackingController) und StorageController verwenden als Schnittstellen

**Comment by lmoedl** [comment]
Dann sag mir mal endlich, in was für einem Format ich die Daten bekomm, die hochgeladen werden sollen. Und wozu brauch ich einen NotificationTrackListener?

**Comment by apoehlmann** [comment]
Der NotificationTrackListener ist ein Template, welches du Implementieren sollst und meinem TrackController geben sollst und darüber bekommst du die Daten.

**Comment by apoehlmann** [comment]
Listenertemplates für die Anbindung sind fertig bei Radar und Track
