### ISSUE TITLE
Controller für Aufbereitung der Daten der Freunde zum Anzeigen

### ISSUE THREAD

**Issue by apoehlmann** [MobileComputingHof/GPSTracker#5]

**Comment by lmoedl** [comment]
In wie fern sollen die Daten aufbereitet werden? Etwas genauer bitte!

**Comment by apoehlmann** [comment]
Vielleicht mal Modelklasse einführen, die verständlicher ist als Positionsmodel und einen getter schreiben der auch was zurück gibt und ich kann nicht synchron auf Daten zugreifen die asynchron geladen werden.
Hinzu kommt, das ich überhaupt nicht weiß von wann die Ortung ist.
```
class Friend{
 private Location lastKnowLocation;
private String ID;
//...
}
```
