### ISSUE TITLE
Klassendiagramme für jedes Workpackage  und Übersicht erstellen

### ISSUE THREAD

**Issue by apoehlmann** [MobileComputingHof/GPSTracker#6]

**Comment by lmoedl** [comment]
Nicht notwendig! Jede Gruppe macht ihre eigene Dokumentation. Diese werden am Ende alle zusammen zu einem Dokument zusammengefügt. 
Dies ist mit Herr Stepping abgeklärt!

**Comment by drui** [comment]
Kein Grund hier zu schließen.
Für ein Paar der Programmteile ist ein Klassendiagramm nicht schlecht. Und sowas gehört in eine gute Doku auch rein.
Auch wenn jeder einen Teil allein machen soll.

**Comment by lmoedl** [comment]
Klassendiagramme sind Pflicht für jeden Teil der Doku, aber es ist kein Supersize-Klassendiagramm für das komplette Projekt notwendig.

**Comment by drui** [comment]
Zufrieden?

**Comment by lmoedl** [comment]
Damit wäre ich zufrieden ;)

**Comment by apoehlmann** [comment]
Das nicht, aber die Verbindungen zu den anderen Workpackages müssen gezeigt werden
