### ISSUE TITLE
Radar realisieren

### ISSUE THREAD

**Issue by apoehlmann** [MobileComputingHof/GPSTracker#9]
Ich hatte mir gedacht, dass wir fürs Erste das Radar auf der Karte(Fragment GPSTracker)  darstellen. 
Später dann den Hintergrund für das Radar anpassen (Karte im Hintergrund durch ein eigenes Bild ersetzen).

**Comment by drui** [comment]
Können wir so machen.

**Comment by lmoedl** [comment]
Für den Anfang ist das ok, aber später müssen das definitv zwei unterschiedliche Screens werden, da es komplett verschiedene Funktionalitäten sind.

**Comment by drui** [comment]
"Später dann den Hintergrund für das Radar anpassen (Karte im Hintergrund durch ein eigenes Bild ersetzen)." 
Also steht nirgends irgendwas davon das es alles auf einem Screen ist.

**Comment by lmoedl** [comment]
Doch, weil oben steht "Fragment GPSTracker" und das für den Anfang dann der selbe Screen sowohl für den Tracker als auch das Radar ist.

**Comment by drui** [comment]
Fürs erste sagt aber dabei eigentlcih alles.
Aber da es nichtmal dein Teil ist, kann es dir doch egal sein wie es gelöst wird.

**Comment by lmoedl** [comment]
Dein Teil ist es auch nicht ;)

**Comment by drui** [comment]
Teilweise schon.

**Comment by lmoedl** [comment]
Dann ist es wohl auch teilweise meiner, da ich ja schließlich die notwendigen Daten speichern und liefern soll.

**Comment by apoehlmann** [comment]
Radarkarte ist online und jetzt fehlt nur noch die Conntection vom @lmoedl

**Comment by apoehlmann** [comment]
Die Anbindung erfolgt über den RadarController
